on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        port: 22
        timeout: 60s
        script: whoami

    - name: Deploy on Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        port: 22
        timeout: 60s
        script: |
          cd ~/projects/bots/Rebel_Bible_Bot
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
          echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}" >> .env
          echo "LINK=${{ secrets.LINK }}" >> .env
          git pull origin main || true
          docker-compose down || true
          docker system prune -f
          docker-compose build --no-cache
          docker-compose up --build -d
